version: "3"
services:
  web:
    container_name: fog-web
    restart: always
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - mongo

  mongo:
    container_name: fog_mongo
    image: mongo
    ports:
      - "27017:27017"
